routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/checkrole', 'MainController@checkRole');

Route::group(['namespace' => 'frontend'], function() {
	Route::get('/', function () {
    	return view('frontend.email');
	});
	Route::get('/lang/{locale}', function($locale) {
		Session::put('locale', $locale);
		return redirect()->back();
	});
	Route::get('/search', [
		'as'	=>	'frontend.email.search',
		'uses'	=>	'MainController@searchEmail'
	]);
	Route::get('/mailgroup', [
		'as'	=>	'frontend.mailgroup',
		'uses'	=>	'MainController@listMailGroup'
	]);
	Route::get('/phone', [
		'as'	=>	'frontend.phone',
		'uses'	=>	'MainController@listPhone'
	]);
	Route::get('/mobile', [
		'as'	=>	'frontend.mobile',
		'uses'	=>	'MainController@listMobile'
	]);
	Route::get('/show/{mail_group_id}', [
		'as'	=>	'frontend.showmember',
		'uses'	=>	'MainController@showMember'
	]);
});

Route::group(['namespace' => 'Backend', 'middleware' => 'auth'], function() {
	Route::get('/home', [
		'as'	=>	'backend.home',
		'uses'	=>	'MainController@index'
	]);

	Route::group(['prefix' => 'user'], function() {
		Route::get('/list', [
			'as'	=>	'backend.user.list',
			'uses'	=>	'UserController@index'
		]);
		Route::get('/create', [
			'as'	=>	'backend.user.create.get',
			'uses'	=>	'UserController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.user.create.post',
			'uses'	=>	'UserController@postCreate'
		]);
		Route::get('/edit/{user_id}', [
			'as'	=>	'backend.user.edit.get',
			'uses'	=>	'UserController@getEdit'
		]);
		Route::post('/edit/{user_id}', [
			'as'	=>	'backend.user.edit.post',
			'uses'	=>	'UserController@postEdit'
		]);
		Route::delete('/delete/{user_id}', [
			'as'	=>	'backend.user.delete',
			'uses'	=>	'UserController@delete'
		]);
	});

	Route::group(['prefix' => 'title'], function() {
		Route::get('/list', [
			'as'	=>	'backend.title.list',
			'uses'	=>	'TitleController@index'
		]);
		Route::get('/search', [
			'as'	=>	'backend.title.search',
			'uses'	=>	'TitleController@search'
		]);
		Route::get('/create', [
			'as'	=>	'backend.title.create.get',
			'uses'	=>	'TitleController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.title.create.post',
			'uses'	=>	'TitleController@postCreate'
		]);
		Route::get('/edit/{title_id}', [
			'as'	=>	'backend.title.edit.get',
			'uses'	=>	'TitleController@getEdit'
		]);
		Route::post('/edit/{title_id}', [
			'as'	=>	'backend.title.edit.post',
			'uses'	=>	'TitleController@postEdit'
		]);
		Route::delete('/delete/{title_id}', [
			'as'	=>	'backend.title.delete',
			'uses'	=>	'TitleController@delete'
		]);
	});

	Route::group(['prefix' => 'setting'], function() {
		Route::get('/changepassword', [
			'as'	=>	'backend.setting.changepassword.get',
			'uses'	=>	'SettingController@getChangePassword'
		]);
		Route::post('/changepassword', [
			'as'	=>	'backend.setting.changepassword.post',
			'uses'	=>	'SettingController@postChangePassword'
		]);
		Route::get('/changelang', [
			'as'	=>	'backend.setting.changelang.get',
			'uses'	=>	'SettingController@getChangeLang'
		]);
		Route::post('/changelang', [
			'as'	=>	'backend.setting.changelang.post',
			'uses'	=>	'SettingController@postChangeLang'
		]);
	});

	Route::group(['prefix' => 'section'], function() {
		Route::get('/list', [
			'as'	=>	'backend.section.list',
			'uses'	=>	'SectionController@index'
		]);
		Route::get('/search', [
			'as'	=>	'backend.section.search',
			'uses'	=>	'SectionController@search'
		]);
		Route::get('/create', [
			'as'	=>	'backend.section.create.get',
			'uses'	=>	'SectionController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.section.create.post',
			'uses'	=>	'SectionController@postCreate'
		]);
		Route::get('/edit/{section_id}', [
			'as'	=>	'backend.section.edit.get',
			'uses'	=>	'SectionController@getEdit'
		]);
		Route::post('/edit/{section_id}', [
			'as'	=>	'backend.section.edit.post',
			'uses'	=>	'SectionController@postEdit'
		]);
		Route::delete('/delete/{section_id}', [
			'as'	=>	'backend.section.delete',
			'uses'	=>	'SectionController@delete'
		]);
	});

	Route::group(['prefix' => 'phone'], function() {
		Route::get('/list', [
			'as'	=>	'backend.phone.list',
			'uses'	=>	'PhoneController@index'
		]);
		Route::get('/create', [
			'as'	=>	'backend.phone.create.get',
			'uses'	=>	'PhoneController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.phone.create.post',
			'uses'	=>	'PhoneController@postCreate'
		]);
		Route::get('/edit/{phone_id}', [
			'as'	=>	'backend.phone.edit.get',
			'uses'	=>	'PhoneController@getEdit'
		]);
		Route::post('/edit/{phone_id}', [
			'as'	=>	'backend.phone.edit.post',
			'uses'	=>	'PhoneController@postEdit'
		]);
		Route::delete('/delete/{phone_id}', [
			'as'	=>	'backend.phone.delete',
			'uses'	=>	'PhoneController@delete'
		]);
	});

	Route::group(['prefix' => 'officer'], function() {
		Route::get('/list', [
			'as'	=>	'backend.officer.list',
			'uses'	=>	'OfficerController@index'
		]);
		Route::get('/search', [
			'as'	=>	'backend.officer.search',
			'uses'	=>	'OfficerController@search'
		]);
		Route::get('/show/{officer_id}', [
			'as'	=>	'backend.officer.show',
			'uses'	=>	'OfficerController@show'
		]);
		Route::get('/create', [
			'as'	=>	'backend.officer.create.get',
			'uses'	=>	'OfficerController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.officer.create.post',
			'uses'	=>	'OfficerController@postCreate'
		]);
		Route::get('/edit/{officer_id}', [
			'as'	=>	'backend.officer.edit.get',
			'uses'	=>	'OfficerController@getEdit'
		]);
		Route::post('/edit/{officer_id}', [
			'as'	=>	'backend.officer.edit.post',
			'uses'	=>	'OfficerController@postEdit'
		]);
		Route::get('/changestatus/{officer_id}', [
			'as'	=>	'backend.officer.changestatus',
			'uses'	=>	'OfficerController@changeStatus'
		]);
	});

	Route::group(['prefix' => 'notice'], function() {
		Route::get('/list', [
			'as'	=>	'backend.notice.list',
			'uses'	=>	'NoticeController@index'
		]);
		Route::get('/new', [
			'as'	=>	'backend.notice.new.get',
			'uses'	=>	'NoticeController@getNoticeNew'
		]);
		Route::post('/new', [
			'as'	=>	'backend.notice.new.post',
			'uses'	=>	'NoticeController@postNoticeNew'
		]);
		Route::get('/resign', [
			'as'	=>	'backend.notice.resign.get',
			'uses'	=>	'NoticeController@getNoticeResign'
		]);
		Route::post('/resign', [
			'as'	=>	'backend.notice.resign.post',
			'uses'	=>	'NoticeController@postNoticeResign'
		]);
	});

	Route::group(['prefix' => 'mobile'], function() {
		Route::get('/list', [
			'as'	=>	'backend.mobile.list',
			'uses'	=>	'MobileController@index'
		]);
		Route::get('/search', [
			'as'	=>	'backend.mobile.search',
			'uses'	=>	'MobileController@search'
		]);
		Route::get('/create', [
			'as'	=>	'backend.mobile.create.get',
			'uses'	=>	'MobileController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.mobile.create.post',
			'uses'	=>	'MobileController@postCreate'
		]);
		Route::get('/edit/{mobile_id}', [
			'as'	=>	'backend.mobile.edit.get',
			'uses'	=>	'MobileController@getEdit'
		]);
		Route::post('/edit/{mobile_id}', [
			'as'	=>	'backend.mobile.edit.post',
			'uses'	=>	'MobileController@postEdit'
		]);
		Route::delete('/delete/{mobile_id}', [
			'as'	=>	'backend.mobile.delete',
			'uses'	=>	'MobileController@delete'
		]);
	});

	Route::group(['prefix' => 'mailgroup'], function() {
		Route::get('/list', [
			'as'	=>	'backend.mailgroup.list',
			'uses'	=>	'MailGroupController@index'
		]);
		Route::get('/search', [
			'as'	=>	'backend.mailgroup.search',
			'uses'	=>	'MailGroupController@search'
		]);
		Route::get('/create', [
			'as'	=>	'backend.mailgroup.create.get',
			'uses'	=>	'MailGroupController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.mailgroup.create.post',
			'uses'	=>	'MailGroupController@postCreate'
		]);
		Route::get('/edit/{mail_group_id}', [
			'as'	=>	'backend.mailgroup.edit.get',
			'uses'	=>	'MailGroupController@getEdit'
		]);
		Route::post('/edit/{mail_group_id}', [
			'as'	=>	'backend.mailgroup.edit.post',
			'uses'	=>	'MailGroupController@postEdit'
		]);
		Route::delete('/delete/{mail_group_id}', [
			'as'	=>	'backend.mailgroup.delete',
			'uses'	=>	'MailGroupController@delete'
		]);
		Route::get('/addmember/{mail_group_id}', [
			'as'	=>	'backend.mailgroup.addmember.get',
			'uses'	=>	'MailGroupController@getAddMember'
		]);
		Route::post('/addmember/{mail_group_id}', [
			'as'	=>	'backend.mailgroup.addmember.post',
			'uses'	=>	'MailGroupController@postAddMember'
		]);
		Route::get('/showmember/{mail_group_id}', [
			'as'	=>	'backend.mailgroup.showmember',
			'uses'	=>	'MailGroupController@showMember'
		]);
		Route::delete('/deletemember/{officer_in_mail_group_id}', [
			'as'	=>	'backend.mailgroup.deletemember',
			'uses'	=>	'MailGroupController@deleteMember'
		]);
	});

	Route::group(['prefix' => 'extension'], function() {
		Route::get('/list', [
			'as'	=>	'backend.extension.list',
			'uses'	=>	'ExtensionController@index'
		]);
		Route::get('/search', [
			'as'	=>	'backend.extension.search',
			'uses'	=>	'ExtensionController@search'
		]);
		Route::get('/create', [
			'as'	=>	'backend.extension.create.get',
			'uses'	=>	'ExtensionController@getCreate'
		]);
		Route::post('/create', [
			'as'	=>	'backend.extension.create.post',
			'uses'	=>	'ExtensionController@postCreate'
		]);
		Route::get('/edit/{extension_id}', [
			'as'	=>	'backend.extension.edit.get',
			'uses'	=>	'ExtensionController@getEdit'
		]);
		Route::post('/edit/{extension_id}', [
			'as'	=>	'backend.extension.edit.post',
			'uses'	=>	'ExtensionController@postEdit'
		]);

app/Models/Phone.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['number', 'branch_id', 'remark_en', 'remark_th'];

    public function getBranch() 
    {
    	return $this->belongsTo('App\Models\Branch', 'branch_id');
    }

    public function extensions() 
    {
    	return $this->hasMany(Extension::class);
    }
}

app/Http/Controllers/Frontend/MainController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Officer;
use App\Models\Department;
use App\Models\Section;
use App\Models\MailGroup;
use App\Models\Mobile;
use App\Models\Phone;

class MainController extends Controller
{
    public function searchEmail(Request $request)
    {
    	$keyword = $request->get('keyword');
    	$category = $request->get('category');
    	$officer = new Officer();

    	switch ($category) {
			case 'all':
				$data['officers'] = $officer->where('firstname_en', 'like', $keyword)
								->orWhere('firstname_th', 'like', '%' . $keyword . '%')
								->orWhere('lastname_en', 'like', $keyword)
								->orWhere('lastname_th', 'like', '%' . $keyword . '%')
								->orWhere('nickname_en', 'like', $keyword)
								->orWhere('nickname_th', 'like', '%' . $keyword . '%')
								->get();
				if (count($data['officers']) == 0) {
					$data['officers'] = $officer->join('departments', 'departments.id', '=', 'officers.department_id')
									->join('sections', 'sections.id', '=', 'officers.section_id')
									->where('departments.code', 'like', $keyword)
									->orWhere('departments.name_en', 'like', '%' . $keyword . '%')
									->orWhere('departments.name_th', 'like', '%' . $keyword . '%')
									->orWhere('sections.name_en', 'like', '%' . $keyword . '%')
									->orWhere('sections.name_th', 'like', '%' . $keyword . '%')
									->get();
				}
				break;
			
			case 'name':
				$data['officers'] = $officer->where('firstname_en', 'like', '%' . $keyword . '%')
								->orWhere('firstname_th', 'like', '%' . $keyword . '%')
								->orWhere('lastname_en', 'like', '%' . $keyword . '%')
								->orWhere('lastname_th', 'like', '%' . $keyword . '%')
								->get();
				break;

			case 'nickname':
				$data['officers'] = $officer->where('nickname_en', 'like', '%' . $keyword . '%')
								->orWhere('nickname_th', 'like', '%' . $keyword . '%')
								->get();
				break;

			case 'department':
				$data['officers'] = Department::with('officers')->get();
				break;

			case 'section':
				$data['officers'] = Section::with('officers')->get();
				break;
		}

    	return view('frontend.email', $data);
    }

    public function listMailGroup()
    {
    	return view('frontend.mailgroup');
    }

    public function showMember()
    {
    	
    }

    public function listPhone()
    {
    	return view('frontend.extension');
    }

    public function listMobile()
    {
    	return view('frontend.mobile');
    }
}

resources/views/frontend/email.blade.php
@extends('frontend.layouts.app')

@section('content')

<div class="ui center aligned inverted container segment">
	<h1 class="ui header">{{ trans('frontend.title') }}</h1>
	<div class="ui hidden divider"></div>
	<form id="searchbox" class="ui large form" method="GET" action="{{ route('frontend.email.search') }}">
		{{ csrf_field() }}
		<div class="three fields">
			<div class="three wide field"></div>
			<div class="ten wide field">
				<div class="ui action input">
					<input type="text" name="keyword" placeholder="{{ trans('frontend.search_box') }}" value="{{ old('keyword') }}">
					<select name="category" class="ui selection dropdown">
						<option value="all">{{ trans('frontend.search_option.all') }}</option>
						<option value="nickname">
							{{ trans('frontend.search_option.nickname') }}
						</option>
						<option value="name">{{ trans('frontend.search_option.name') }}</option>
						<option value="department">
							{{ trans('frontend.search_option.department') }}
						</option>
						<option value="section">{{ trans('frontend.search_option.section') }}</option>
					</select>
					<button class="ui submit orange large button" type="submit">
						{{ trans('frontend.search') }}
					</button>
				</div>
			</div>
			<div class="three wide field"></div>
		</div>
	</form>
	<div class="ui hidden divider"></div>
	<table class="ui striped celled center aligned table">
		<thead>
			<tr>
				<th>#</th>
				<th>{{ trans('frontend.table.name') }}</th>
				<th>{{ trans('frontend.table.nickname') }}</th>
				<th>{{ trans('frontend.table.department') }}</th>
				<th>{{ trans('frontend.table.email') }}</th>
			</tr>
		</thead>
		<tbody>
			@if (isset($_GET['keyword']))
				@forelse ($officers as $index => $officer)
					@if ($_SESSION['locale'] == 'en')
						<tr>
							<td>{{ ++$index }}</td>
							<td>{{ $officer['firstname_en'] . ' ' . $officer['lastname_en'] }}</td>
							<td>{{ $officer['nickname_en'] }}</td>
							<td>{{ $officer->getDepartment['name_en'] . '(' . $officer->getDepartment['code'] . ')' }}</td>
							<td>{{ $officer['email'] }}</td>
						</tr>
					@else
						<tr>
							<td>{{ ++$index }}</td>
							<td>{{ $officer['firstname_th'] . ' ' . $officer['lastname_th'] }}</td>
							<td>{{ $officer['nickname_th'] }}</td>
							<td>{{ $officer->getDepartment['name_th'] . '(' . $officer->getDepartment['code'] . ')' }}</td>
							<td>{{ $officer['email'] }}</td>
						</tr>
					@endif
				@empty
					<tr>
						<td colspan="5">{{ trans('frontend.table.data_not_found') }}</td>
					</tr>
				@endforelse
			@else
				<tr>
					<td colspan="5">{{ trans('frontend.table.search_line') }}</td>
				</tr>
			@endif
		</tbody>
	</table>
</div>

@endsection

resources/views/frontend/extension.blade.php
@extends('frontend.layouts.app')

@section('content')

<div class="ui center aligned inverted container segment">
	<h1 class="ui header">{{ trans('frontend.extension') }}</h1>
	<div class="ui hidden divider"></div>
	<table class="ui striped celled table">
		<thead>
			<tr class="ui center aligned">
				<th>#</th>
				<th>{{ trans('frontend.table.branch') }}</th>
				<th>{{ trans('frontend.table.number') }}</th>
			</tr>
		</thead>
		<tbody>
			@forelse ($phones as $index => $phone)
				<tr>
					<td class="ui center aligned">{{ ++$index }}</td>
					@if ($_SESSION['locale'] == 'en')
						<td></td>
					@else
						<td></td>
					@endif
					<td></td>
				</tr>				
			@empty
				<tr class="ui center aligned">
					<td colspan="3">{{ trans('frontend.table.data_not_found') }}</td>
				</tr>
			@endforelse
		</tbody>
	</table>
	
</div>

@endsection

resources/views/frontend/mailgroup.blade.php
@extends('frontend.layouts.app')

@section('content')

<div class="ui center aligned inverted container segment">
	<h1 class="ui header">{{ trans('frontend.mailgroup') }}</h1>
	<div class="ui hidden divider"></div>
	<table class="ui striped celled table">
		<thead>
			<tr class="ui center aligned">
				<th>#</th>
				<th>{{ trans('frontend.table.group_name') }}</th>
				<th>{{ trans('frontend.table.email') }}</th>
			</tr>
		</thead>
		<tbody>
			@forelse ($mailgroups as $index => $mailgroup)
				<tr>
					<td class="ui center aligned">{{ ++$index }}</td>
					@if ($_SESSION['locale'] == 'en')
						<td></td>
					@else
						<td></td>
					@endif
					<td></td>
				</tr>
			@empty
				<tr class="ui center aligned">
					<td colspan="3">{{ trans('frontend.table.data_not_found') }}</td>
				</tr>
			@endforelse
		</tbody>
	</table>
</div>

@endsection

resources/views/frontend/member.blade.php
@extends('frontend.layouts.app')

@section('content')

<div class="ui center aligned inverted container segment">
	@if ($_SESSION['locale'] == 'en')
		<h1 class="ui header">{{ trans('frontend.member') }}</h1>
	@else
		<h1 class="ui header">{{ trans('frontend.member') }}</h1>
	@endif
	<div class="ui hidden divider"></div>
	<table class="ui striped celled table">
		<thead>
			<tr class="ui center aligned">
				<th>#</th>
				<th>{{ trans('frontend.table.name') }}</th>
				<th>{{ trans('frontend.table.nickname') }}</th>
				<th>{{ trans('frontend.table.email') }}</th>
			</tr>
		</thead>
		<tbody>
			@forelse ($members as $index => $member)
				<tr>
					<td class="ui center aligned">{{ ++index }}</td>
					@if ($_SESSION['locale'] == 'en')
						<td></td>
						<td></td>
					@else
						<td></td>
						<td></td>
					@endif
					<td></td>
				</tr>
			@empty
				<tr class="ui center aligned">
					<td colspan="4">{{ trans('frontend.table.data_not_found') }}</td>
				</tr>
			@endforelse
		</tbody>
	</table>
</div>

@endsection

resources/views/frontend/mobile.blade.php
@extends('frontend.layouts.app')

@section('content')

<div class="ui center aligned inverted container segment">
	<h1 class="ui header">{{ trans('frontend.mobile') }}</h1>
	<div class="ui hidden divider"></div>
	<table class="ui striped celled table">
		<thead>
			<tr class="ui center aligned">
				<th>#</th>
				<th>{{ trans('frontend.table.group_name') }}</th>
				<th>{{ trans('frontend.table.number') }}</th>
			</tr>
		</thead>
		<tbody>
			@forelse ($mobiles as $index => $mobile)
				<tr>
					<td>{{ ++$index }}</td>
					@if ($_SESSION['locale'] == 'en')
						<td></td>
					@else
						<td></td>
					@endif
					<td></td>
				</tr>
			@empty
				<tr>
					<td colspan="3">{{ trans('frontend.table.data_not_found') }}</td>
				</tr>
			@endforelse
		</tbody>
	</table>
</div>

@endsection